### ISSUE TITLE
make test: ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by karel-brinda** [OndrejSladky/kmercamel#27]
```
$ make test
./kmerstest
[==========] Running 26 tests from 24 test suites.
[----------] Global test environment set-up.
[----------] 1 test from ReadFastaTest
[ RUN      ] ReadFastaTest.ReadFasta
[       OK ] ReadFastaTest.ReadFasta (1 ms)
[----------] 1 test from ReadFastaTest (1 ms total)

[----------] 1 test from AddKMersFromSequenceTest
[ RUN      ] AddKMersFromSequenceTest.AddKMersFromSequence
[       OK ] AddKMersFromSequenceTest.AddKMersFromSequence (0 ms)
[----------] 1 test from AddKMersFromSequenceTest (0 ms total)

[----------] 1 test from FilterKMersWithComplementTest
[ RUN      ] FilterKMersWithComplementTest.FilterKMersWithComplement
[       OK ] FilterKMersWithComplementTest.FilterKMersWithComplement (0 ms)
[----------] 1 test from FilterKMersWithComplementTest (0 ms total)

[----------] 1 test from ConstructKMersTest
[ RUN      ] ConstructKMersTest.ConstructKMers
[       OK ] ConstructKMersTest.ConstructKMers (0 ms)
[----------] 1 test from ConstructKMersTest (0 ms total)

[----------] 1 test from BitSuffixTest
[ RUN      ] BitSuffixTest.BitSuffix
[       OK ] BitSuffixTest.BitSuffix (0 ms)
[----------] 1 test from BitSuffixTest (0 ms total)

[----------] 1 test from BitPrefixTest
[ RUN      ] BitPrefixTest.BitPrefix
[       OK ] BitPrefixTest.BitPrefix (0 ms)
[----------] 1 test from BitPrefixTest (0 ms total)

[----------] 1 test from NucleotideToIntTest
[ RUN      ] NucleotideToIntTest.NucleotideToInt
[       OK ] NucleotideToIntTest.NucleotideToInt (0 ms)
[----------] 1 test from NucleotideToIntTest (0 ms total)

[----------] 1 test from ComplementaryNucleotideTest
[ RUN      ] ComplementaryNucleotideTest.ComplementaryNucleotide
[       OK ] ComplementaryNucleotideTest.ComplementaryNucleotide (0 ms)
[----------] 1 test from ComplementaryNucleotideTest (0 ms total)

[----------] 1 test from NumberToKMerTest
[ RUN      ] NumberToKMerTest.NumberToKMer
[       OK ] NumberToKMerTest.NumberToKMer (0 ms)
[----------] 1 test from NumberToKMerTest (0 ms total)

[----------] 1 test from KMerToNumberTest
[ RUN      ] KMerToNumberTest.KMerToNumber
[       OK ] KMerToNumberTest.KMerToNumber (0 ms)
[----------] 1 test from KMerToNumberTest (0 ms total)

[----------] 2 tests from ReverseComplementTest
[ RUN      ] ReverseComplementTest.Int
[       OK ] ReverseComplementTest.Int (0 ms)
[ RUN      ] ReverseComplementTest.String
[       OK ] ReverseComplementTest.String (0 ms)
[----------] 2 tests from ReverseComplementTest (0 ms total)

[----------] 1 test from OverlapHamiltonianPathTest
[ RUN      ] OverlapHamiltonianPathTest.OverlapHamiltonianPath
[       OK ] OverlapHamiltonianPathTest.OverlapHamiltonianPath (0 ms)
[----------] 1 test from OverlapHamiltonianPathTest (0 ms total)

[----------] 1 test from GreedyTest
[ RUN      ] GreedyTest.Greedy
[       OK ] GreedyTest.Greedy (0 ms)
[----------] 1 test from GreedyTest (0 ms total)

[----------] 1 test from SuffixTest
[ RUN      ] SuffixTest.Suffix
[       OK ] SuffixTest.Suffix (0 ms)
[----------] 1 test from SuffixTest (0 ms total)

[----------] 1 test from SuperstringFromPathTest
[ RUN      ] SuperstringFromPathTest.SuperstringFromPath
[       OK ] SuperstringFromPathTest.SuperstringFromPath (0 ms)
[----------] 1 test from SuperstringFromPathTest (0 ms total)

[----------] 1 test from OverlapHamiltonianPathACTest
[ RUN      ] OverlapHamiltonianPathACTest.OverlapHamiltonianPathAC
[       OK ] OverlapHamiltonianPathACTest.OverlapHamiltonianPathAC (0 ms)
[----------] 1 test from OverlapHamiltonianPathACTest (0 ms total)

[----------] 2 tests from ACAutomatonTest
[ RUN      ] ACAutomatonTest.ConstructTrie
[       OK ] ACAutomatonTest.ConstructTrie (0 ms)
[ RUN      ] ACAutomatonTest.ConstructBackwardEdges
[       OK ] ACAutomatonTest.ConstructBackwardEdges (0 ms)
[----------] 2 tests from ACAutomatonTest (0 ms total)

[----------] 1 test from GreedyACTest
[ RUN      ] GreedyACTest.GreedyAC
[       OK ] GreedyACTest.GreedyAC (0 ms)
[----------] 1 test from GreedyACTest (0 ms total)

[----------] 1 test from RightExtensionTest
[ RUN      ] RightExtensionTest.RightExtension
[       OK ] RightExtensionTest.RightExtension (0 ms)
[----------] 1 test from RightExtensionTest (0 ms total)

[----------] 1 test from LeftExtensionTest
[ RUN      ] LeftExtensionTest.LeftExtension
[       OK ] LeftExtensionTest.LeftExtension (0 ms)
[----------] 1 test from LeftExtensionTest (0 ms total)

[----------] 1 test from NextGeneralizedSimplitigTest
[ RUN      ] NextGeneralizedSimplitigTest.NextGeneralizedSimplitig
[       OK ] NextGeneralizedSimplitigTest.NextGeneralizedSimplitig (0 ms)
[----------] 1 test from NextGeneralizedSimplitigTest (0 ms total)

[----------] 1 test from GreedyGeneralizedSimplitigsTest
[ RUN      ] GreedyGeneralizedSimplitigsTest.GreedyGeneralizedSimplitigs
[       OK ] GreedyGeneralizedSimplitigsTest.GreedyGeneralizedSimplitigs (0 ms)
[----------] 1 test from GreedyGeneralizedSimplitigsTest (0 ms total)

[----------] 1 test from ExtensionACTest
[ RUN      ] ExtensionACTest.ExtensionAC
[       OK ] ExtensionACTest.ExtensionAC (0 ms)
[----------] 1 test from ExtensionACTest (0 ms total)

[----------] 1 test from GreedyGeneralizedSimplitigsACTest
[ RUN      ] GreedyGeneralizedSimplitigsACTest.GreedyGeneralizedSimplitigsAC
[       OK ] GreedyGeneralizedSimplitigsACTest.GreedyGeneralizedSimplitigsAC (0 ms)
[----------] 1 test from GreedyGeneralizedSimplitigsACTest (0 ms total)

[----------] Global test environment tear-down
[==========] 26 tests from 24 test suites ran. (2 ms total)
[  PASSED  ] 26 tests.
./convert_superstring_unittest.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
./verify.py ./spneumoniae.fa
Failed to open input file './bin/merged.jf'
Testing with support for reverse complements:
Testing greedy:
Traceback (most recent call last):
  File "/Users/karel/github/my/k-mers/./verify.py", line 80, in <module>
    success &= verify_instance(path, k, a, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karel/github/my/k-mers/./verify.py", line 50, in verify_instance
    key, value = f.readline().split()
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
make: *** [verify] Error 1

```

**Comment by OndrejSladky** [comment]
Is this issue still relevant on your PC?

**Comment by OndrejSladky** [comment]
The input format of the script has changed significantly since the issue creation and I also tested it now on MacOS and now it works fine. If a similar issue persists, feel free to reopen.
